services:
  postgres:
    image: postgres:latest
    container_name: scalable_postgres
    restart: always
    environment:
      POSTGRES_USER: scalable
      POSTGRES_PASSWORD: Pass
      POSTGRES_DB: scalabledb
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: